name         'puppet-module-arc'
version      '1.2.0'
source       'git@github.com:Phil-Friderici/puppet-module-arc.git'
author       'phil.friderici@ericsson.com'
license      'Apache-2.0'
summary      'Manage OpenAFS additions'
description  'Manage OpenAFS additions'
project_page 'https://github.com/Phil-Friderici/puppet-module-arc'

dependency 'puppetlabs/stdlib', '>= 4.2.0'
